fix: release development pipeline (#147)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -75,21 +75,30 @@ jobs:
             NEXT_PUBLIC_APP_URL=https://${{ env.DOMAIN }}
           push: true
           tags: |
-            ${{ env.IMAGE_NAME }}-panel-${{ matrix.environment }}:latest
-            ${{ env.IMAGE_NAME }}-panel-${{ matrix.environment }}:${{ env.VERSION }}
-            ${{ env.IMAGE_NAME }}-panel-${{ matrix.environment }}:${{ github.sha }}
+            ${{ env.IMAGE_NAME }}-${{ matrix.environment }}:latest
+            ${{ env.IMAGE_NAME }}-${{ matrix.environment }}:${{ env.VERSION }}
+            ${{ env.IMAGE_NAME }}-${{ matrix.environment }}:${{ github.sha }}
 
   deploy-development:
     name: Deploy to development
     environment:
       name: development
       url: https://ptatosol.com
-    env:
-      VERSION: ${{ fromJson(needs.release.outputs.publishedPackages)[0].version }}
     runs-on: ubuntu-latest
     needs:
       - release
       - build-and-push-image
+    timeout-minutes: 30
+    env:
+      VERSION: ${{ fromJson(needs.release.outputs.publishedPackages)[0].version }}
+      ENVIRONMENT: development
+      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
+      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
+      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
+      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
+      POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
+      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
+      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -103,8 +112,8 @@ jobs:
 
       - name: Test Hostname Resolution
         run: |
-          ping -c 3 sensepro-server-dev
-          nc -zv sensepro-server-dev 22
+          ping -c 3 sensepro-server-dev || (echo "Hostname resolution failed!" && exit 1)
+          nc -zv sensepro-server-dev 22 || (echo "Port 22 is not accessible!" && exit 1)
 
       - name: Prepare SSH Directory
         run: |
@@ -117,26 +126,13 @@ jobs:
         run: ssh -o ConnectTimeout=30 "cicd@sensepro-server-dev" "echo 'SSH connection successful!'"
 
       - name: Configure Docker Stack
-        run: docker context create remote --docker "host=ssh://cicd@sensepro-server-dev"
-
-      - name: List Docker Contexts
-        run: docker context ls
-
-      - name: Use Remote Docker Context
-        run: docker context use remote
+        run: |
+          docker context create remote --docker "host=ssh://cicd@sensepro-server-dev"
+          docker context ls
+          docker context use remote
 
       - name: Docker Stack Deploy
-        env:
-          ENVIRONMENT: development
-          VERSION: ${{ env.VERSION }}
-          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
-          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
-          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
-          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
-          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
-          RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
-          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
-        run: docker stack deploy -c docker-stack.yaml "${{ vars.DOCKER_STACK_NAME }}"
+        run: docker stack deploy -c docker-stack.yaml sensepro
 
       - name: Setup Node.js 20
         uses: actions/setup-node@v3
@@ -181,7 +177,7 @@ jobs:
       - name: Docker Stack Deploy
         uses: cssnr/stack-deploy-action@v1
         with:
-          name: ${{ vars.DOCKER_STACK_NAME }}
+          name: sensepro
           file: docker-stack.yaml
           host: ${{ vars.DOMAIN_NAME }}
           user: cicd
